
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cloud-edge-v1-nodemanagement
  failurePolicy: Fail
  name: mnodemanagement.kb.io
  rules:
  - apiGroups:
    - cloud.edge
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodemanagements
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cloud-edge-v1-nodemanagement
  failurePolicy: Fail
  name: vnodemanagement.kb.io
  rules:
  - apiGroups:
    - cloud.edge
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodemanagements
  sideEffects: None
