// Copyright @ 2022 Lenovo. All rights reserved
// Confidential and Restricted
// This file was generated using one of kubebuilder templated ( https://github.com/kubernetes-sigs/kubebuilder/tree/master/pkg/plugins/golang/v2/scaffolds/internal/templates) distributed under the terms of Apache-2.0 license.

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "igitlab.lenovo.com/lecp/mec/bailu/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// NodeManagements returns a NodeManagementInformer.
	NodeManagements() NodeManagementInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// NodeManagements returns a NodeManagementInformer.
func (v *version) NodeManagements() NodeManagementInformer {
	return &nodeManagementInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
