# permissions for end users to view nodemanagements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodemanagement-viewer-role
rules:
- apiGroups:
  - edge.cloud
  resources:
  - nodemanagements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edge.cloud
  resources:
  - nodemanagements/status
  verbs:
  - get
