# permissions for end users to edit nodemanagements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodemanagement-editor-role
rules:
- apiGroups:
  - edge.cloud
  resources:
  - nodemanagements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edge.cloud
  resources:
  - nodemanagements/status
  verbs:
  - get
