// Copyright @ 2022 Lenovo. All rights reserved
// Confidential and Restricted
// This file was generated using one of kubebuilder templated ( https://github.com/kubernetes-sigs/kubebuilder/tree/master/pkg/plugins/golang/v2/scaffolds/internal/templates) distributed under the terms of Apache-2.0 license.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "igitlab.lenovo.com/lecp/mec/bailu/client/clientset/versioned/typed/cloud.edge/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCloudV1 struct {
	*testing.Fake
}

func (c *FakeCloudV1) NodeManagements() v1.NodeManagementInterface {
	return &FakeNodeManagements{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCloudV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
